### ISSUE TITLE
Is there a way to do this on windows

### ISSUE THREAD

**Issue by Linkdash2019** [industry-advance/industry-advance#3]
All I have is a windows computer and a raspberry pi 4 with raspian I can’t use Linux at all

**Comment by casept** [comment]
There are no plans to support building on non-Linux. You can use a Linux VM. Building on the Pi may also work, but I have never tested non-x86 build machines.

Also, keep in mind that the game is in a pretty broken state. It's intended only for development right now, not actually playing it.
